//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarionetteTips
{
    using System;
    using System.Collections.Generic;
    
    using System.Runtime.Serialization;
    [DataContract]
    public partial class City
    {
        public City()
        {
            this.Team = new HashSet<Team>();
        }
    
    		[DataMember]
    	    public int ID { get; set; }
    		[DataMember]
    	    public string Title { get; set; }
    		[DataMember]
    	    public int CountryID { get; set; }
    	    public string ModifiedBy { get; set; }
    	    public System.DateTime ModifiedDate { get; set; }
    	    public string CreatedBy { get; set; }
    	    public System.DateTime CreatedDate { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual ICollection<Team> Team { get; set; }
    }
}
