//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarionetteTips
{
    using System;
    using System.Collections.Generic;
    
    using System.Runtime.Serialization;
    [DataContract]
    public partial class Game
    {
        public Game()
        {
            this.UserGameExpectedResult = new HashSet<UserGameExpectedResult>();
        }
    
    		[DataMember]
    	    public int ID { get; set; }
    		[DataMember]
    	    public int HomeTeamID { get; set; }
    		[DataMember]
    	    public int AwayTeamID { get; set; }
    		[DataMember]
    	    public Nullable<int> HomeTeamResult { get; set; }
    		[DataMember]
    	    public Nullable<int> AwayTeamResult { get; set; }
    		[DataMember]
    	    public int GroupID { get; set; }
    		[DataMember]
    	    public Nullable<System.DateTime> Date { get; set; }
    	    public string ModifiedBy { get; set; }
    	    public System.DateTime ModifiedDate { get; set; }
    	    public string CreatedBy { get; set; }
    	    public System.DateTime CreatedDate { get; set; }
    
        public virtual Team Team { get; set; }
        public virtual Group Group { get; set; }
        public virtual Team Team1 { get; set; }
        public virtual ICollection<UserGameExpectedResult> UserGameExpectedResult { get; set; }
    }
}
