//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarionetteTips
{
    using System;
    using System.Collections.Generic;
    
    using System.Runtime.Serialization;
    [DataContract]
    public partial class UserLogins
    {
    		[DataMember]
    	    public int ID { get; set; }
    		[DataMember]
    	    public int UserID { get; set; }
    		[DataMember]
    	    public System.DateTime TimeForLogin { get; set; }
    		[DataMember]
    	    public string Browser { get; set; }
    		[DataMember]
    	    public string BrowserVersion { get; set; }
    }
}
