//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarionetteTips
{
    using System;
    using System.Collections.Generic;
    
    using System.Runtime.Serialization;
    [DataContract]
    public partial class webpages_Membership
    {
    		[DataMember]
    	    public int UserId { get; set; }
    		[DataMember]
    	    public Nullable<System.DateTime> CreateDate { get; set; }
    		[DataMember]
    	    public string ConfirmationToken { get; set; }
    		[DataMember]
    	    public Nullable<bool> IsConfirmed { get; set; }
    		[DataMember]
    	    public Nullable<System.DateTime> LastPasswordFailureDate { get; set; }
    		[DataMember]
    	    public int PasswordFailuresSinceLastSuccess { get; set; }
    	    public string Password { get; set; }
    		[DataMember]
    	    public Nullable<System.DateTime> PasswordChangedDate { get; set; }
    		[DataMember]
    	    public string PasswordSalt { get; set; }
    		[DataMember]
    	    public string PasswordVerificationToken { get; set; }
    		[DataMember]
    	    public Nullable<System.DateTime> PasswordVerificationTokenExpirationDate { get; set; }
    }
}
