DECLARE @ModifiedBy NVARCHAR(200) = 'Country Set-up'

INSERT INTO Country VALUES('Aruba', 'ABW', 'ABW.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Afghanistan', 'AFG', 'AFG.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Angola', 'AGO', 'AGO.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Anguilla', 'AIA', 'AIA.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Åland Islands', 'ALA', 'ALA.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Albania', 'ALB', 'ALB.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Andorra', 'AND', 'AND.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('United Arab Emirates', 'ARE', 'ARE.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Argentina', 'ARG', 'ARG.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Armenia', 'ARM', 'ARM.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('American Samoa', 'ASM', 'ASM.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Antarctica', 'ATA', 'ATA.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('French Southern Territories', 'ATF', 'ATF.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Antigua and Barbuda', 'ATG', 'ATG.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Australia', 'AUS', 'AUS.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Austria', 'AUT', 'AUT.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Azerbaijan', 'AZE', 'AZE.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Burundi', 'BDI', 'BDI.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Belgium', 'BEL', 'BEL.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Benin', 'BEN', 'BEN.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Bonaire, Sint Eustatius and Saba', 'BES', 'BES.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Burkina Faso', 'BFA', 'BFA.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Bangladesh', 'BGD', 'BGD.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Bulgaria', 'BGR', 'BGR.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Bahrain', 'BHR', 'BHR.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Bahamas', 'BHS', 'BHS.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Bosnia and Herzegovina', 'BIH', 'BIH.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Saint Barthélemy', 'BLM', 'BLM.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Belarus', 'BLR', 'BLR.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Belize', 'BLZ', 'BLZ.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Bermuda', 'BMU', 'BMU.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Bolivia, Plurinational State of', 'BOL', 'BOL.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Brazil', 'BRA', 'BRA.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Barbados', 'BRB', 'BRB.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Brunei Darussalam', 'BRN', 'BRN.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Bhutan', 'BTN', 'BTN.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Bouvet Island', 'BVT', 'BVT.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Botswana', 'BWA', 'BWA.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Central African Republic', 'CAF', 'CAF.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Canada', 'CAN', 'CAN.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Cocos (Keeling) Islands', 'CCK', 'CCK.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Switzerland', 'CHE', 'CHE.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Chile', 'CHL', 'CHL.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('China', 'CHN', 'CHN.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Ivory Coast', 'CIV', 'CIV.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Cameroon', 'CMR', 'CMR.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Congo, the Democratic Republic of the', 'COD', 'COD.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Congo', 'COG', 'COG.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Cook Islands', 'COK', 'COK.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Colombia', 'COL', 'COL.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Comoros', 'COM', 'COM.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Cabo Verde', 'CPV', 'CPV.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Costa Rica', 'CRI', 'CRI.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Cuba', 'CUB', 'CUB.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Curaçao', 'CUW', 'CUW.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Christmas Island', 'CXR', 'CXR.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Cayman Islands', 'CYM', 'CYM.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Cyprus', 'CYP', 'CYP.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Czech Republic', 'CZE', 'CZE.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Germany', 'DEU', 'DEU.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Djibouti', 'DJI', 'DJI.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Dominica', 'DMA', 'DMA.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Denmark', 'DNK', 'DNK.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Dominican Republic', 'DOM', 'DOM.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Algeria', 'DZA', 'DZA.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Ecuador', 'ECU', 'ECU.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('England', 'ENG', 'ENG.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Egypt', 'EGY', 'EGY.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Eritrea', 'ERI', 'ERI.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Western Sahara', 'ESH', 'ESH.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Spain', 'ESP', 'ESP.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Estonia', 'EST', 'EST.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Ethiopia', 'ETH', 'ETH.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Finland', 'FIN', 'FIN.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Fiji', 'FJI', 'FJI.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Falkland Islands (Malvinas)', 'FLK', 'FLK.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('France', 'FRA', 'FRA.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Faroe Islands', 'FRO', 'FRO.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Micronesia, Federated States of', 'FSM', 'FSM.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Gabon', 'GAB', 'GAB.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('United Kingdom', 'GBR', 'GBR.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Georgia', 'GEO', 'GEO.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Guernsey', 'GGY', 'GGY.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Ghana', 'GHA', 'GHA.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Gibraltar', 'GIB', 'GIB.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Guinea', 'GIN', 'GIN.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Guadeloupe', 'GLP', 'GLP.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Gambia', 'GMB', 'GMB.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Guinea-Bissau', 'GNB', 'GNB.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Equatorial Guinea', 'GNQ', 'GNQ.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Greece', 'GRC', 'GRC.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Grenada', 'GRD', 'GRD.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Greenland', 'GRL', 'GRL.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Guatemala', 'GTM', 'GTM.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('French Guiana', 'GUF', 'GUF.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Guam', 'GUM', 'GUM.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Guyana', 'GUY', 'GUY.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Hong Kong', 'HKG', 'HKG.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Heard Island and McDonald Islands', 'HMD', 'HMD.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Honduras', 'HND', 'HND.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Croatia', 'HRV', 'HRV.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Haiti', 'HTI', 'HTI.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Hungary', 'HUN', 'HUN.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Indonesia', 'IDN', 'IDN.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Isle of Man', 'IMN', 'IMN.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('India', 'IND', 'IND.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('British Indian Ocean Territory', 'IOT', 'IOT.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Ireland', 'IRL', 'IRL.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Iran', 'IRN', 'IRN.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Iraq', 'IRQ', 'IRQ.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Iceland', 'ISL', 'ISL.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Israel', 'ISR', 'ISR.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Italy', 'ITA', 'ITA.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Jamaica', 'JAM', 'JAM.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Jersey', 'JEY', 'JEY.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Jordan', 'JOR', 'JOR.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Japan', 'JPN', 'JPN.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Kazakhstan', 'KAZ', 'KAZ.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Kenya', 'KEN', 'KEN.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Kyrgyzstan', 'KGZ', 'KGZ.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Cambodia', 'KHM', 'KHM.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Kiribati', 'KIR', 'KIR.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Saint Kitts and Nevis', 'KNA', 'KNA.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('South Korea', 'KOR', 'KOR.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Kuwait', 'KWT', 'KWT.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Lao People''s Democratic Republic', 'LAO', 'LAO.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Lebanon', 'LBN', 'LBN.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Liberia', 'LBR', 'LBR.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Libya', 'LBY', 'LBY.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Saint Lucia', 'LCA', 'LCA.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Liechtenstein', 'LIE', 'LIE.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Sri Lanka', 'LKA', 'LKA.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Lesotho', 'LSO', 'LSO.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Lithuania', 'LTU', 'LTU.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Luxembourg', 'LUX', 'LUX.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Latvia', 'LVA', 'LVA.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Macao', 'MAC', 'MAC.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Saint Martin (French part)', 'MAF', 'MAF.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Morocco', 'MAR', 'MAR.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Monaco', 'MCO', 'MCO.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Moldova, Republic of', 'MDA', 'MDA.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Madagascar', 'MDG', 'MDG.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Maldives', 'MDV', 'MDV.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Mexico', 'MEX', 'MEX.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Marshall Islands', 'MHL', 'MHL.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Macedonia, the former Yugoslav Republic of', 'MKD', 'MKD.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Mali', 'MLI', 'MLI.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Malta', 'MLT', 'MLT.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Myanmar', 'MMR', 'MMR.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Montenegro', 'MNE', 'MNE.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Mongolia', 'MNG', 'MNG.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Northern Mariana Islands', 'MNP', 'MNP.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Mozambique', 'MOZ', 'MOZ.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Mauritania', 'MRT', 'MRT.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Montserrat', 'MSR', 'MSR.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Martinique', 'MTQ', 'MTQ.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Mauritius', 'MUS', 'MUS.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Malawi', 'MWI', 'MWI.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Malaysia', 'MYS', 'MYS.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Mayotte', 'MYT', 'MYT.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Namibia', 'NAM', 'NAM.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('New Caledonia', 'NCL', 'NCL.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Niger', 'NER', 'NER.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Norfolk Island', 'NFK', 'NFK.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Nigeria', 'NGA', 'NGA.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Nicaragua', 'NIC', 'NIC.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Niue', 'NIU', 'NIU.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Netherlands', 'NLD', 'NLD.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Norway', 'NOR', 'NOR.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Nepal', 'NPL', 'NPL.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Nauru', 'NRU', 'NRU.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('New Zealand', 'NZL', 'NZL.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Oman', 'OMN', 'OMN.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Pakistan', 'PAK', 'PAK.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Panama', 'PAN', 'PAN.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Pitcairn', 'PCN', 'PCN.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Peru', 'PER', 'PER.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Philippines', 'PHL', 'PHL.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Palau', 'PLW', 'PLW.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Papua New Guinea', 'PNG', 'PNG.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Poland', 'POL', 'POL.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Puerto Rico', 'PRI', 'PRI.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Korea, Democratic People''s Republic of', 'PRK', 'PRK.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Portugal', 'PRT', 'PRT.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Paraguay', 'PRY', 'PRY.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Palestine, State of', 'PSE', 'PSE.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('French Polynesia', 'PYF', 'PYF.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Qatar', 'QAT', 'QAT.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Réunion', 'REU', 'REU.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Romania', 'ROU', 'ROU.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Russia', 'RUS', 'RUS.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Rwanda', 'RWA', 'RWA.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Saudi Arabia', 'SAU', 'SAU.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Sudan', 'SDN', 'SDN.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Senegal', 'SEN', 'SEN.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Singapore', 'SGP', 'SGP.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('South Georgia and the South Sandwich Islands', 'SGS', 'SGS.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Saint Helena, Ascension and Tristan da Cunha', 'SHN', 'SHN.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Svalbard and Jan Mayen', 'SJM', 'SJM.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Solomon Islands', 'SLB', 'SLB.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Sierra Leone', 'SLE', 'SLE.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('El Salvador', 'SLV', 'SLV.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('San Marino', 'SMR', 'SMR.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Somalia', 'SOM', 'SOM.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Saint Pierre and Miquelon', 'SPM', 'SPM.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Serbia', 'SRB', 'SRB.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('South Sudan', 'SSD', 'SSD.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Sao Tome and Principe', 'STP', 'STP.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Suriname', 'SUR', 'SUR.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Slovakia', 'SVK', 'SVK.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Slovenia', 'SVN', 'SVN.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Sweden', 'SWE', 'SWE.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Swaziland', 'SWZ', 'SWZ.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Sint Maarten (Dutch part)', 'SXM', 'SXM.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Seychelles', 'SYC', 'SYC.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Syrian Arab Republic', 'SYR', 'SYR.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Turks and Caicos Islands', 'TCA', 'TCA.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Chad', 'TCD', 'TCD.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Togo', 'TGO', 'TGO.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Thailand', 'THA', 'THA.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Tajikistan', 'TJK', 'TJK.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Tokelau', 'TKL', 'TKL.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Turkmenistan', 'TKM', 'TKM.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Timor-Leste', 'TLS', 'TLS.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Tonga', 'TON', 'TON.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Trinidad and Tobago', 'TTO', 'TTO.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Tunisia', 'TUN', 'TUN.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Turkey', 'TUR', 'TUR.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Tuvalu', 'TUV', 'TUV.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Taiwan, Province of China', 'TWN', 'TWN.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Tanzania, United Republic of', 'TZA', 'TZA.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Uganda', 'UGA', 'UGA.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Ukraine', 'UKR', 'UKR.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('United States Minor Outlying Islands', 'UMI', 'UMI.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Uruguay', 'URY', 'URY.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('United States', 'USA', 'USA.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Uzbekistan', 'UZB', 'UZB.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Holy See (Vatican City State)', 'VAT', 'VAT.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Saint Vincent and the Grenadines', 'VCT', 'VCT.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Venezuela, Bolivarian Republic of', 'VEN', 'VEN.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Virgin Islands, British', 'VGB', 'VGB.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Virgin Islands, U.S.', 'VIR', 'VIR.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Viet Nam', 'VNM', 'VNM.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Vanuatu', 'VUT', 'VUT.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Wallis and Futuna', 'WLF', 'WLF.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Samoa', 'WSM', 'WSM.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Yemen', 'YEM', 'YEM.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('South Africa', 'ZAF', 'ZAF.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Zambia', 'ZMB', 'ZMB.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
INSERT INTO Country VALUES('Zimbabwe', 'ZWE', 'ZWE.png', @ModifiedBy, GETUTCDATE(), @ModifiedBy, GETUTCDATE())
