CREATE TABLE Country
(
	ID INT IDENTITY(1,1) CONSTRAINT pk_Country_ID PRIMARY KEY,
	Title NVARCHAR(100),
	CountryCode VARCHAR(3),
	FlagImg NVARCHAR(255),
	ModifiedBy NVARCHAR(100) NOT NULL,
	ModifiedDate DATETIME NOT NULL,
	CreatedBy NVARCHAR(100) NOT NULL,
	CreatedDate DATETIME NOT NULL
)

CREATE TABLE City
(
	ID INT IDENTITY(1,1) CONSTRAINT pk_City_ID PRIMARY KEY,
	Title NVARCHAR(100),
	CountryID INT NOT NULL,
	ModifiedBy NVARCHAR(100) NOT NULL,
	ModifiedDate DATETIME NOT NULL,
	CreatedBy NVARCHAR(100) NOT NULL,
	CreatedDate DATETIME NOT NULL
)
ALTER TABLE City ADD CONSTRAINT fk_City_CountryID_Country_ID FOREIGN KEY(CountryID) REFERENCES Country(ID)

CREATE TABLE Team
(
	ID INT IDENTITY(1,1) CONSTRAINT pk_Team_ID PRIMARY KEY,
	Title NVARCHAR(100) NOT NULL,
	Logo NVARCHAR(255),
	CityID INT,
	ModifiedBy NVARCHAR(100) NOT NULL,
	ModifiedDate DATETIME NOT NULL,
	CreatedBy NVARCHAR(100) NOT NULL,
	CreatedDate DATETIME NOT NULL
)

ALTER TABLE Team ADD CONSTRAINT fk_Team_CityID_City_ID FOREIGN KEY(CityID) REFERENCES City(ID)

CREATE TABLE Competition
(
	ID INT IDENTITY(1,1) CONSTRAINT pk_Competition_ID PRIMARY KEY,
	Title NVARCHAR(100) NOT NULL,
	StartDate DATETIME,
	EndDate DATETIME,
	CountryID INT NOT NULL,
	ModifiedBy NVARCHAR(100) NOT NULL,
	ModifiedDate DATETIME NOT NULL,
	CreatedBy NVARCHAR(100) NOT NULL,
	CreatedDate DATETIME NOT NULL
)

ALTER TABLE Competition ADD CONSTRAINT fk_Competition_CountryID_Country_ID FOREIGN KEY(CountryID) REFERENCES Country(ID)

CREATE TABLE [Group]
(
	ID INT IDENTITY(1,1) CONSTRAINT pk_Group_ID PRIMARY KEY,
	Title NVARCHAR(100) NOT NULL,
	CompetitionID INT NOT NULL,
	ModifiedBy NVARCHAR(100) NOT NULL,
	ModifiedDate DATETIME NOT NULL,
	CreatedBy NVARCHAR(100) NOT NULL,
	CreatedDate DATETIME NOT NULL
)

ALTER TABLE [Group] ADD CONSTRAINT fk_Group_CompetitionID_Competition_ID FOREIGN KEY(CompetitionID) REFERENCES Competition(ID)

CREATE TABLE Game
(
	ID INT IDENTITY(1,1) CONSTRAINT pk_Game_ID PRIMARY KEY,
	HomeTeamID INT NOT NULL,
	AwayTeamID INT NOT NULL,
	HomeTeamResult INT,
	AwayTeamResult INT,
	GroupID INT NOT NULL,
	[Date] DATETIME,
	ModifiedBy NVARCHAR(100) NOT NULL,
	ModifiedDate DATETIME NOT NULL,
	CreatedBy NVARCHAR(100) NOT NULL,
	CreatedDate DATETIME NOT NULL
)

ALTER TABLE Game ADD CONSTRAINT fk_Game_HomeTeamID_Team_ID FOREIGN KEY(HomeTeamID) REFERENCES Team(ID)
ALTER TABLE Game ADD CONSTRAINT fk_Game_AwayTeamID_Team_ID FOREIGN KEY(AwayTeamID) REFERENCES Team(ID)
ALTER TABLE Game ADD CONSTRAINT fk_Game_GroupID_Team_ID FOREIGN KEY(GroupID) REFERENCES [Group](ID)

CREATE TABLE [User]
(
	ID INT IDENTITY(1,1) CONSTRAINT pk_User_ID PRIMARY KEY,
	Email NVARCHAR(255) NOT NULL,
	FirstName NVARCHAR(255) NOT NULL,
	LastName NVARCHAR(255) NOT NULL,
	[Password] NVARCHAR(255) NOT NULL,
	ModifiedBy NVARCHAR(100) NOT NULL,
	ModifiedDate DATETIME NOT NULL,
	CreatedBy NVARCHAR(100) NOT NULL,
	CreatedDate DATETIME NOT NULL
)

CREATE TABLE UserGameExpectedResult
(
	ID INT IDENTITY(1,1) CONSTRAINT pk_UserGameExpectedResult_ID PRIMARY KEY,
	UserID INT NOT NULL,
	GameID INT NOT NULL,
	HomeResult INT NOT NULL,
	AwayResult INT NOT NULL,
	ModifiedBy NVARCHAR(100) NOT NULL,
	ModifiedDate DATETIME NOT NULL,
	CreatedBy NVARCHAR(100) NOT NULL,
	CreatedDate DATETIME NOT NULL
)
ALTER TABLE UserGameExpectedResult ADD CONSTRAINT fk_UserGameExpectedResult_UserID_User_ID FOREIGN KEY(UserID) REFERENCES [User](ID)
ALTER TABLE UserGameExpectedResult ADD CONSTRAINT fk_UserGameExpectedResult_GameID_Game_ID FOREIGN KEY(GameID) REFERENCES Game(ID)

CREATE TABLE UserCompetition
(
	ID INT IDENTITY(1,1) CONSTRAINT pk_UserCompetition_ID PRIMARY KEY,
	UserID INT NOT NULL,
	CompetitionID INT NOT NULL,
	ModifiedBy NVARCHAR(100) NOT NULL,
	ModifiedDate DATETIME NOT NULL,
	CreatedBy NVARCHAR(100) NOT NULL,
	CreatedDate DATETIME NOT NULL
)
ALTER TABLE UserCompetition ADD CONSTRAINT fk_UserCompetition_UserID_User_ID FOREIGN KEY(UserID) REFERENCES [User](ID)
ALTER TABLE UserCompetition ADD CONSTRAINT fk_UserCompetition_CompetitionID_Competition_ID FOREIGN KEY(CompetitionID) REFERENCES Competition(ID)

CREATE SCHEMA LOG

CREATE TABLE LOG.UserLogins
(
	ID INT IDENTITY(1,1) CONSTRAINT pk_UserCompetition_ID PRIMARY KEY,
	UserID INT NOT NULL,
	TimeForLogin DATETIME NOT NULL,
	Browser NVARCHAR(100),
	BrowserVersion NVARCHAR(10)
)
/*
DROP TABLE UserCompetition
DROP TABLE UserGameExpectedResult
DROP TABLE Game
DROP TABLE [Group]
DROP TABLE Competition
DROP TABLE Team
DROP TABLE City
DROP TABLE Country
DROP TABLE [User]
*/